int jumlahkaryawan = 0;
bool adagambar = true;

List<Map<String, dynamic>> founduser = [];

List<Map<String, String>> datakaryawan = [
  {
    'nama': 'Nadzila Afifa',
    'jabatan': 'Accounting Manager',
    'nomor': '09385839246',
    'email': 'example@email.com',
    'imageurl':
        'https://media.licdn.com/dms/image/C5603AQF4UMVifTENjA/profile-displayphoto-shrink_800_800/0/1630468969909?e=2147483647&v=beta&t=udbP56QjpMVwOfl-m7Z_NLiXWxU_WjnCTw8LOHgbPNw',
    'namaperusahaan': 'PT Gojek Indonesia',
    'cabang': 'Surabaya',
    'departement': 'Indihome',
    'posisipekerjaan': 'Accounting Manager',
    'levelpekerjaan': 'Tetap',
    'statuspekerjaan': '',
    'tanggalbergabung': '',
    'masakerja': '',
    'idkaryawan': '',
    'jeniskelamin': '',
    'tanggallahir': '',
    'tempatlahir': '',
    'statuspernikahan': '',
    'agama': '',
    'golongandarah': '',
    'instagram': '@annonymouse'
  },
  {
    'nama': 'Karina Santika',
    'jabatan': 'English Translator',
    'nomor': '09385839246',
    'email': 'example@email.com',
    'imageurl':
        'https://media.licdn.com/dms/image/C5603AQGNQzV3KSgoQg/profile-displayphoto-shrink_800_800/0/1660284631987?e=2147483647&v=beta&t=nlOwOQFoyKmAka1IhrZNrwEiCn-WTKggsuEdDtFs270',
    'namaperusahaan': '',
    'cabang': '',
    'departement': '',
    'posisipekerjaan': '',
    'levelpekerjaan': '',
    'statuspekerjaan': '',
    'tanggalbergabung': '',
    'masakerja': '',
    'idkaryawan': '',
    'jeniskelamin': '',
    'tanggallahir': '',
    'tempatlahir': '',
    'statuspernikahan': '',
    'agama': '',
    'golongandarah': '',
    'instagram': '@annonymouse'
  },
  {
    'nama': 'Intan Nurita Sari',
    'jabatan': 'Accounting Manager',
    'nomor': '09385839246',
    'email': 'example@email.com',
    'imageurl':
        'https://media.licdn.com/dms/image/C5603AQHK1Q2_PzWEwA/profile-displayphoto-shrink_800_800/0/1634366567499?e=1683158400&v=beta&t=7cVDzVNJml0F17c7qxHX18mHptzL6ABWKDgzsgdR48g',
    'namaperusahaan': '',
    'cabang': '',
    'departement': '',
    'posisipekerjaan': '',
    'levelpekerjaan': '',
    'statuspekerjaan': '',
    'tanggalbergabung': '',
    'masakerja': '',
    'idkaryawan': '',
    'jeniskelamin': '',
    'tanggallahir': '',
    'tempatlahir': '',
    'statuspernikahan': '',
    'agama': '',
    'golongandarah': '',
    'instagram': '@annonymouse'
  },
  {
    'nama': 'Ariska Riris',
    'jabatan': 'Accounting Manager',
    'nomor': '09385839246',
    'email': 'example@email.com',
    'imageurl':
        'https://media.licdn.com/dms/image/C5603AQEpLLe7GUZ-Fw/profile-displayphoto-shrink_800_800/0/1627022282091?e=2147483647&v=beta&t=AQ_RkkT0mmbU0WcFvSQ-c-6N1JEjAvfHEKXfkc9Ohc0',
    'namaperusahaan': '',
    'cabang': '',
    'departement': '',
    'posisipekerjaan': '',
    'levelpekerjaan': '',
    'statuspekerjaan': '',
    'tanggalbergabung': '',
    'masakerja': '',
    'idkaryawan': '',
    'jeniskelamin': 'wanita',
    'tanggallahir': '',
    'tempatlahir': '',
    'statuspernikahan': '',
    'agama': '',
    'golongandarah': '',
    'instagram': '@annonymouse'
  },
  {
    'nama': 'Arum Purwita Sari',
    'jabatan': 'Accounting Manager',
    'nomor': '09385839246',
    'email': 'example@email.com',
    'imageurl':
        'https://media.licdn.com/dms/image/D5603AQEJZLMKFcYW_A/profile-displayphoto-shrink_800_800/0/1677652695634?e=1683158400&v=beta&t=uC3BYaus8_ukTV8CvWwYwuP-fEnjn5jmDu4e7e8GtNE',
    'namaperusahaan': '',
    'cabang': '',
    'departement': '',
    'posisipekerjaan': '',
    'levelpekerjaan': '',
    'statuspekerjaan': '',
    'tanggalbergabung': '',
    'masakerja': '',
    'idkaryawan': '',
    'jeniskelamin': 'pria',
    'tanggallahir': '',
    'tempatlahir': '',
    'statuspernikahan': '',
    'agama': '',
    'golongandarah': '',
    'instagram': '@annonymouse'
  },
  {
    'nama': 'Nadzila Afifa',
    'jabatan': 'Accounting Manager',
    'nomor': '09385839246',
    'email': 'example@email.com',
    'imageurl':
        'https://media.licdn.com/dms/image/C5603AQF4UMVifTENjA/profile-displayphoto-shrink_800_800/0/1630468969909?e=2147483647&v=beta&t=udbP56QjpMVwOfl-m7Z_NLiXWxU_WjnCTw8LOHgbPNw',
    'namaperusahaan': 'PT Gojek Indonesia',
    'cabang': 'Surabaya',
    'departement': 'Indihome',
    'posisipekerjaan': 'Accounting Manager',
    'levelpekerjaan': 'Tetap',
    'statuspekerjaan': '',
    'tanggalbergabung': '',
    'masakerja': '',
    'idkaryawan': '',
    'jeniskelamin': '',
    'tanggallahir': '',
    'tempatlahir': '',
    'statuspernikahan': '',
    'agama': '',
    'golongandarah': '',
    'instagram': '@annonymouse'
  },
  {
    'nama': 'Karina Santika',
    'jabatan': 'English Translator',
    'nomor': '09385839246',
    'email': 'example@email.com',
    'imageurl':
        'https://media.licdn.com/dms/image/C5603AQGNQzV3KSgoQg/profile-displayphoto-shrink_800_800/0/1660284631987?e=2147483647&v=beta&t=nlOwOQFoyKmAka1IhrZNrwEiCn-WTKggsuEdDtFs270',
    'namaperusahaan': '',
    'cabang': '',
    'departement': '',
    'posisipekerjaan': '',
    'levelpekerjaan': '',
    'statuspekerjaan': '',
    'tanggalbergabung': '',
    'masakerja': '',
    'idkaryawan': '',
    'jeniskelamin': '',
    'tanggallahir': '',
    'tempatlahir': '',
    'statuspernikahan': '',
    'agama': '',
    'golongandarah': '',
    'instagram': '@annonymouse'
  },
  {
    'nama': 'Intan Nurita Sari',
    'jabatan': 'Accounting Manager',
    'nomor': '09385839246',
    'email': 'example@email.com',
    'imageurl':
        'https://media.licdn.com/dms/image/C5603AQHK1Q2_PzWEwA/profile-displayphoto-shrink_800_800/0/1634366567499?e=1683158400&v=beta&t=7cVDzVNJml0F17c7qxHX18mHptzL6ABWKDgzsgdR48g',
    'namaperusahaan': '',
    'cabang': '',
    'departement': '',
    'posisipekerjaan': '',
    'levelpekerjaan': '',
    'statuspekerjaan': '',
    'tanggalbergabung': '',
    'masakerja': '',
    'idkaryawan': '',
    'jeniskelamin': '',
    'tanggallahir': '',
    'tempatlahir': '',
    'statuspernikahan': '',
    'agama': '',
    'golongandarah': '',
    'instagram': '@annonymouse'
  },
  {
    'nama': 'Ariska Riris',
    'jabatan': 'Accounting Manager',
    'nomor': '09385839246',
    'email': 'example@email.com',
    'imageurl':
        'https://media.licdn.com/dms/image/C5603AQEpLLe7GUZ-Fw/profile-displayphoto-shrink_800_800/0/1627022282091?e=2147483647&v=beta&t=AQ_RkkT0mmbU0WcFvSQ-c-6N1JEjAvfHEKXfkc9Ohc0',
    'namaperusahaan': '',
    'cabang': '',
    'departement': '',
    'posisipekerjaan': '',
    'levelpekerjaan': '',
    'statuspekerjaan': '',
    'tanggalbergabung': '',
    'masakerja': '',
    'idkaryawan': '',
    'jeniskelamin': 'wanita',
    'tanggallahir': '',
    'tempatlahir': '',
    'statuspernikahan': '',
    'agama': '',
    'golongandarah': '',
    'instagram': '@annonymouse'
  },
  {
    'nama': 'Arum Purwita Sari',
    'jabatan': 'Accounting Manager',
    'nomor': '09385839246',
    'email': '',
    'imageurl':
        'https://media.licdn.com/dms/image/D5603AQEJZLMKFcYW_A/profile-displayphoto-shrink_800_800/0/1677652695634?e=1683158400&v=beta&t=uC3BYaus8_ukTV8CvWwYwuP-fEnjn5jmDu4e7e8GtNE',
    'namaperusahaan': '',
    'cabang': '',
    'departement': '',
    'posisipekerjaan': '',
    'levelpekerjaan': '',
    'statuspekerjaan': '',
    'tanggalbergabung': '',
    'masakerja': '',
    'idkaryawan': '',
    'jeniskelamin': 'pria',
    'tanggallahir': '',
    'tempatlahir': '',
    'statuspernikahan': '',
    'agama': '',
    'golongandarah': '',
    'instagram': '@annonymouse'
  },
];
