// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4bRinYV3WF3UOwVS4KYCj0A3D20qPjuY',
    appId: '1:493485927140:android:735a1b59e2835da67f1af1',
    messagingSenderId: '493485927140',
    projectId: 'qonnected-2a114',
    databaseURL: 'https://qonnected-2a114-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qonnected-2a114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbEgajHTf1aroiD4Ci8QPd7rLYLuo4caI',
    appId: '1:493485927140:ios:be87783bacb408b77f1af1',
    messagingSenderId: '493485927140',
    projectId: 'qonnected-2a114',
    databaseURL: 'https://qonnected-2a114-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qonnected-2a114.appspot.com',
    iosClientId: '493485927140-eap2jhh9pru9dvlv26pj2aib4k6ejuoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.qonnectedApp',
  );
}
