// List<ProfileModel> ProfileModelFromJson(String str) => List<ProfileModel>.from(
//     json.decode(str).map((x) => ProfileModel.fromJson(x)));

// String ProfileModelToJson(List<ProfileModel> data) =>
//     json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class ProfileModel {
  final String? id,
      // username,
      // avatar_url,
      fullname,
      email,
      date_of_birth,
      // registration_id,
      date_joined,
      phone,
      // user_id,
      nik,
      nip,
      // company_name,
      // company_group_id,
      place_of_birth,
      religion,
      bank_account_number,
      // marital_status,
      npwp,
      // position,
      // activities,
      // worker_status,
      // employee_identification,
      address,
      instagram,
      linkedin,
      portofolio_url,
      tiktok,
      // identity_number,
      gender;

  ProfileModel({
    this.gender,
    // this.company_name,
    // this.user_id,
    this.nik,
    this.nip,
    // this.company_group_id,
    this.place_of_birth,
    this.religion,
    this.bank_account_number,
    // this.marital_status,
    this.npwp,
    // this.activities,
    this.address,
    this.instagram,
    this.linkedin,
    this.portofolio_url,
    this.tiktok,
    this.id,
    // this.username,
    // this.avatar_url,
    this.fullname,
    this.email,
    this.date_of_birth,
    // this.registration_id,
    this.date_joined,
    this.phone,
    // this.position,
    // this.worker_status,
    // this.employee_identification,
    // this.identity_number
  });

  factory ProfileModel.fromJson(Map<dynamic, dynamic> json) {
    return ProfileModel(
      id: json['id'].toString(),
      // username: json['username'] ?? '-',
      // avatar_url: json['avatar_url'] ?? '-',
      fullname: json['fullname'].toString() ?? '-',
      email: json['email'].toString() ?? '-',
      date_of_birth: json['date_of_birth'].toString() ?? '-',
      // registration_id: json['registration_id'] ?? '-',
      date_joined: json['date_joined'].toString() ?? '-',
      phone: json['phone'].toString() ?? '-',
      // deleted: json['deleted'],
      // position: json['position'] ?? '-',
      // company_id: json['company_id'],
      // worker_status: json['worker_status'] ?? '-',
      // employee_identification: json['employee_identification'] ?? '-',
      // identity_number: json['identity_number'] ?? '-',
      // user_id: json['user_id'] ?? '-',
      nik: json['nik'].toString(),
      nip: json['nip'].toString(),
      // company_group_id: json['company_group_id'],
      place_of_birth: json['place_of_birth'].toString(),
      religion: json['religion'].toString(),
      bank_account_number: json['bank_account_number'].toString(),
      // marital_status: json['marital_status'],
      npwp: json['npwp'].toString(),
      // activities: json['activities'],
      address: json['address'].toString(),
      instagram: json['instagram'].toString(),
      linkedin: json['linkedin'].toString(),
      portofolio_url: json['portofolio'].toString(),
      tiktok: json['tiktok'].toString(),
      gender: json['gender'].toString(),
      // company_name: json['company_name']
    );
  }

  Map<String, dynamic> toJson() => {
        "id": id,
        // "username": username,
        // "avatar_url": avatar_url,
        "fullname": fullname,
        "email": email,
        "date_of_birth": date_of_birth,
        // "registration_id": registration_id,
        "date_joined": date_joined,
        "phone": phone,
        // "deleted": deleted,
        // "company_id": company_id,
        // "position": position,
        // "worker_status": worker_status,
        // "employee_identification": employee_identification,
        // "identity_number": identity_number,
        // "user_id": user_id,
        "nik": nik,
        "nip": nip,
        // "company_group_id": company_group_id,
        "place_of_birth": place_of_birth,
        "religion": religion,
        "bank_account_number": bank_account_number,
        // "marital_status": marital_status,
        "npwp": npwp,
        // "activities": activities,
        "address": address,
        "instagram": instagram,
        "portofolio_url": portofolio_url,
        "tiktok": tiktok,
        "gender": gender,
        // "company_name": company_name
      };
}
